#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
betterlockscreen -w

~/.config/bspwm/monitors.sh

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config border_width         2
bspc config focused_border_color "#2a9dfb"
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 25

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating center=true

~/.config/polybar/launch.sh &

